Third draft severity modelling. Issues in v8SevLoss().__call__()
list_feat_parts = [xi.view(feats[0].shape[0], self.no, -1) for xi in feats]
RuntimeError: shape '[21, 99, -1]' is invalid for input of size 96600000

Also, there is still issues w/ 5 fields in augmenting.RandomPersective.
Occasionally found bboxes.shape[1] = 4 instead of 5, and once found it to be 44 at line:
ultralytics/utils/instance.py:58

Have a look and see how OBB got around this problem.